version: '3'

services:
    x-memcached:
        image: memcached
    x-redis:
        image: redis
    x-benchmark:
        build: .
        volumes:
            - /tmp:/code
    x-benchmark-memcached:
        image: x-benchmark
        command: java -Dmode=false -jar x-benchmark-memcached/target/x-benchmark-memcached-1.0.jar
        ports:
            - "8888:8888"
        depends_on:
            - x-memcached
    x-benchmark-redis:
        image: x-benchmark
        command: java -Dmode=false -jar x-benchmark-redis/target/x-benchmark-redis-1.0.jar
        ports:
            - "9999:9999"
        depends_on:
            - x-redis