version: '3'

services:
    x-memcached:
        image: memcached
    x-redis:
        image: redis
    x-mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: asdf
    x-benchmark-thrift-server:
        buidld: .
        command: java -jar x-benchmark-thrift/target/x-benchmark-thrift-1.0.jar
        ports:
            - "6666:6666"
    x-benchmark-memcached:
        build: .
        command: java -Dmode=false -jar x-benchmark-memcached/target/x-benchmark-memcached-1.0.jar
        ports:
            - "8888:8888"
        depends_on:
            - x-memcached
    x-benchmark-redis:
        build: .
        command: java -Dmode=false -jar x-benchmark-redis/target/x-benchmark-redis-1.0.jar
        ports:
            - "9999:9999"
        depends_on:
            - x-redis
    x-benchmark-mysql:
        build: .
        command: java -Dmode=false -jar x-benchmark-mysql/target/x-benchmark-mysql-1.0.jar
        ports:
            - "5555:5555"
        depends_on:
            - x-mysql